CREATE TABLE UTENTI (
TESSERA int NOT NULL PRIMARY KEY,
NOME char(254) NOT NULL,
COGNOME char(254)NOT NULL,
TELEFONO char(254) NOT NULL
);

CREATE TABLE LIBRI (
CODICE int NOT NULL PRIMARY KEY,
TITOLO char(254) NOT NULL,
AUTORI char(254) DEFAULT 'Anonimo',
NOTE varchar(300)
);

CREATE TABLE PRESTITI (
CODICELIBRO int NOT NULL,
TESSERA int NOT NULL,
DATA_IN date NOT NULL,
DATA_OUT date,
PRIMARY KEY (CODICELIBRO, TESSERA, DATA_IN),
FOREIGN KEY (CODICELIBRO) REFERENCES LIBRI(CODICE) ON DELETE CASCADE,
FOREIGN KEY (TESSERA) REFERENCES UTENTI(TESSERA) ON DELETE CASCADE,
CHECK (DATA_IN <= DATA_OUT OR DATA_IN IS NULL)
);

-- Inserimento di Utenti
INSERT INTO UTENTI (TESSERA, NOME, COGNOME, TELEFONO) VALUES
(1, 'Mario', 'Rossi', '1234567890'),
(2, 'Luisa', 'Verdi', '0987654321'),
(3, 'Giovanni', 'Bianchi', '2345678901'),
(4, 'Anna', 'Neri', '3456789012');

-- Inserimento di Libri
INSERT INTO LIBRI (CODICE, TITOLO, AUTORI, NOTE) VALUES
(101, 'Il Signore degli Anelli', 'J.R.R. Tolkien', NULL),
(102, '1984', 'George Orwell', 'Romanzo distopico'),
(103, 'Il Nome della Rosa', 'Umberto Eco', 'Un grande classico'),
(104, 'Fahrenheit 451', 'Ray Bradbury', 'Una critica alla censura');

-- Inserimento di Prestiti
INSERT INTO PRESTITI (CODICELIBRO, TESSERA, DATA_IN, DATA_OUT) VALUES
(101, 1, '2024-10-01', NULL), -- Prestito attivo
(102, 2, '2024-09-25', '2024-09-30'), -- Prestito completato
(103, 3, '2024-09-25', NULL), -- Prestito attivo
(104, 4, '2024-10-03', '2024-10-05'); -- Prestito completato


UPDATE UTENTI
SET NOME = 'Matteo', COGNOME = 'Gattobigio', TELEFONO = '3922558472'
WHERE TESSERA = 2;

UPDATE LIBRI
SET NOTE = 'federico è un gay signori ooo'
WHERE CODICE = 103;

UPDATE PRESTITI
SET DATA_IN = '2017-09-30'
WHERE CODICELIBRO = 102;

DELETE FROM UTENTI
WHERE TESSERA = 1;

DELETE FROM LIBRI
WHERE CODICE = 101;

SELECT * FROM LIBRI WHERE AUTORI LIKE '%G%' AND TITOLO LIKE '%1984%';

SELECT * FROM UTENTI WHERE COGNOME LIKE 'Gattobigio%';

SELECT * FROM PRESTITI WHERE DAY(PRESTITI.DATA_IN) = 25;

SELECT * FROM PRESTITI WHERE YEAR(PRESTITI.DATA_IN) != YEAR(PRESTITI.DATA_OUT);

SELECT p.CODICELIBRO FROM UTENTI u JOIN PRESTITI p ON u.TESSERA = p.TESSERA 
WHERE u.NOME='Luisa' AND u.COGNOME='Verdi' AND u.TELEFONO='0987654321'

SELECT p.CODICELIBRO FROM UTENTI u JOIN PRESTITI p ON u.TESSERA = p.TESSERA 
WHERE YEAR(p.DATA_IN)>2023 AND MONTH(p.DATA_IN)>09

SELECT p.CODICELIBRO FROM UTENTI u JOIN PRESTITI p ON u.TESSERA = p.TESSERA 
JOIN LIBRI l ON l.CODICE = p.CODICELIBRO 
WHERE l.TITOLO ='Il Nome della Rosa' AND l.AUTORI = 'Umberto Eco'

SELECT u.tessera, u.nome, u.cognome, COUNT(p.codicelibro) AS numero_prestiti
FROM UTENTI u
JOIN PRESTITI p ON u.tessera = p.tessera
WHERE YEAR(p.data_in) = 2017
GROUP BY u.TESSERA, u.nome, u.cognome
HAVING COUNT(p.codicelibro) >= 2;

SELECT u.TESSERA FROM UTENTI u 
JOIN PRESTITI p ON p.TESSERA = u.TESSERA 
WHERE YEAR(p.DATA_in) != 2017;

SELECT U.* FROM UTENTI u 
WHERE NOT EXISTS (
	SELECT 1
	FROM PRESTITI p
	WHERE p.TESSERA = u.TESSERA AND YEAR(p.data_out) != 2024
);

